name: Build

on: push

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Style
        run: python3 -m black --check .

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Documentation
        run: pydocstyle main.py

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: All unit tests pass
        run: python3 -m pytest

  unit-tests-cov:
    name: Unit tests
    runs-on: ubuntu-latest

    outputs:
      cov_output: ${{ steps.cov.outputs.cov }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Coverage is at least 80%
        id: cov
        run: python3 -m pytest --cov=main --cov-fail-under=80 --cov-report json && \
          echo "::set-output name=cov::$(cat *coverage*.json)"

  cov-badge:
    name: Update Coverage Badge
    runs-on: ubuntu-latest
    needs: unit-tests-cov
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy coverage file from coverage job
        run: echo ${{needs.unit-tests-cov.outputs.cov_output}} > coverage.json

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main