name: Build

on: push

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Style
        run: python3 -m black --check .

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Documentation
        run: pydocstyle main.py

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: All unit tests pass
        run: python3 -m pytest

  unit-tests-cov:
    name: Unit tests
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Coverage is at least 80%
        run: python3 -m pytest --cov=main --cov-fail-under=80 --cov-report json