name: Build

on: push

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Style
        run: make check_style

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    container: antoinebrunet1/word_reactor_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Documentation
        run: make check_docs

  unit-tests-cov:
    name: Unit tests coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Coverage is at least 80%
        run: |
          python3 -m pip install pytest-cov discord.py pytest pytest-mock python-dotenv pytest-asyncio flask
          make check_cov_with_report

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main