name: Main

on: push

jobs:
  documentation-checker:
    name: Documentation Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Documentation Checker
        run: |
          python3 -m pip install pydocstyle
          pydocstyle main.py

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: All Unit Tests Pass
        run: |
          python3 -m pip install discord.py
          python3 -m pip install pytest
          python3 -m pip install pytest-mock
          python3 -m pip install python-dotenv
          python3 -m pytest

      - name: Coverage Is At Least 80%
        run: |
          python3 -m pip install pytest-cov
          python3 -m pytest --cov=main --cov-fail-under=80