name: Main

on: push

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Style
        run: |
          python3 -m pip install black
          python3 -m black --check .

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Documentation
        run: |
          python3 -m pip install pydocstyle
          pydocstyle main.py

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: All unit tests pass
        run: |
          python3 -m pip install discord.py pytest pytest-mock python-dotenv pytest-asyncio
          python3 -m pytest

      - name: Coverage is at least 80%
        run: |
          python3 -m pip install pytest-cov
          python3 -m pytest --cov=main --cov-fail-under=80