name: Main

on: push

jobs:
  documentation-checker:
    name: Documentation Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Documentation Checker
        run: |
          python3 -m pip install pydocstyle
          pydocstyle ${{ github.workspace }}/main.py